config/routes.rb
Seat::Application.routes.draw do

  ActiveAdmin.routes(self)

  resources :servers
  resources :omniauth_callbacks
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :users do
    resources :reservations
  end


  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new'
    get 'sign_out', :to => 'devise/sessions#destroy'
  end
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/home/sign_in', to: 'home#sign_in', as: 'home_sign_in'
  root :to => "home#index"

end
#                      admin_root GET      /admin(.:format)                                admin/dashboard#index
#                 admin_dashboard GET      /admin/dashboard(.:format)                      admin/dashboard#index
# batch_action_admin_reservations POST     /admin/reservations/batch_action(.:format)      admin/reservations#batch_action
#              admin_reservations GET      /admin/reservations(.:format)                   admin/reservations#index
#                                 POST     /admin/reservations(.:format)                   admin/reservations#create
#           new_admin_reservation GET      /admin/reservations/new(.:format)               admin/reservations#new
#          edit_admin_reservation GET      /admin/reservations/:id/edit(.:format)          admin/reservations#edit
#               admin_reservation GET      /admin/reservations/:id(.:format)               admin/reservations#show
#                                 PATCH    /admin/reservations/:id(.:format)               admin/reservations#update
#                                 PUT      /admin/reservations/:id(.:format)               admin/reservations#update
#                                 DELETE   /admin/reservations/:id(.:format)               admin/reservations#destroy
#      batch_action_admin_servers POST     /admin/servers/batch_action(.:format)           admin/servers#batch_action
#                   admin_servers GET      /admin/servers(.:format)                        admin/servers#index
#                                 POST     /admin/servers(.:format)                        admin/servers#create
#                new_admin_server GET      /admin/servers/new(.:format)                    admin/servers#new
#               edit_admin_server GET      /admin/servers/:id/edit(.:format)               admin/servers#edit
#                    admin_server GET      /admin/servers/:id(.:format)                    admin/servers#show
#                                 PATCH    /admin/servers/:id(.:format)                    admin/servers#update
#                                 PUT      /admin/servers/:id(.:format)                    admin/servers#update
#                                 DELETE   /admin/servers/:id(.:format)                    admin/servers#destroy
#       batch_action_admin_tables POST     /admin/tables/batch_action(.:format)            admin/tables#batch_action
#                    admin_tables GET      /admin/tables(.:format)                         admin/tables#index
#                                 POST     /admin/tables(.:format)                         admin/tables#create
#                 new_admin_table GET      /admin/tables/new(.:format)                     admin/tables#new
#                edit_admin_table GET      /admin/tables/:id/edit(.:format)                admin/tables#edit
#                     admin_table GET      /admin/tables/:id(.:format)                     admin/tables#show
#                                 PATCH    /admin/tables/:id(.:format)                     admin/tables#update
#                                 PUT      /admin/tables/:id(.:format)                     admin/tables#update
#                                 DELETE   /admin/tables/:id(.:format)                     admin/tables#destroy
#                      admin_user POST     /admin/users/:id(.:format)                      admin/users#create
#                                 PUT      /admin/users/:id(.:format)                      admin/users#update
#        batch_action_admin_users POST     /admin/users/batch_action(.:format)             admin/users#batch_action
#                     admin_users GET      /admin/users(.:format)                          admin/users#index
#                                 POST     /admin/users(.:format)                          admin/users#create
#                  new_admin_user GET      /admin/users/new(.:format)                      admin/users#new
#                 edit_admin_user GET      /admin/users/:id/edit(.:format)                 admin/users#edit
#                                 GET      /admin/users/:id(.:format)                      admin/users#show
#                                 PATCH    /admin/users/:id(.:format)                      admin/users#update
#                                 PUT      /admin/users/:id(.:format)                      admin/users#update
#                                 DELETE   /admin/users/:id(.:format)                      admin/users#destroy
#                  admin_comments GET      /admin/comments(.:format)                       admin/comments#index
#                                 POST     /admin/comments(.:format)                       admin/comments#create
#                   admin_comment GET      /admin/comments/:id(.:format)                   admin/comments#show
#                         servers GET      /servers(.:format)                              servers#index
#                                 POST     /servers(.:format)                              servers#create
#                      new_server GET      /servers/new(.:format)                          servers#new
#                     edit_server GET      /servers/:id/edit(.:format)                     servers#edit
#                          server GET      /servers/:id(.:format)                          servers#show
#                                 PATCH    /servers/:id(.:format)                          servers#update
#                                 PUT      /servers/:id(.:format)                          servers#update
#                                 DELETE   /servers/:id(.:format)                          servers#destroy
#              omniauth_callbacks GET      /omniauth_callbacks(.:format)                   omniauth_callbacks#index
#                                 POST     /omniauth_callbacks(.:format)                   omniauth_callbacks#create
#           new_omniauth_callback GET      /omniauth_callbacks/new(.:format)               omniauth_callbacks#new
#          edit_omniauth_callback GET      /omniauth_callbacks/:id/edit(.:format)          omniauth_callbacks#edit
#               omniauth_callback GET      /omniauth_callbacks/:id(.:format)               omniauth_callbacks#show
#                                 PATCH    /omniauth_callbacks/:id(.:format)               omniauth_callbacks#update
#                                 PUT      /omniauth_callbacks/:id(.:format)               omniauth_callbacks#update
#                                 DELETE   /omniauth_callbacks/:id(.:format)               omniauth_callbacks#destroy
#                new_user_session GET      /users/sign_in(.:format)                        devise/sessions#new
#                    user_session POST     /users/sign_in(.:format)                        devise/sessions#create
#            destroy_user_session DELETE   /users/sign_out(.:format)                       devise/sessions#destroy
#         user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                 omniauth_callbacks#passthru {:provider=>/facebook/}
#          user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)          omniauth_callbacks#(?-mix:facebook)
#                   user_password POST     /users/password(.:format)                       devise/passwords#create
#               new_user_password GET      /users/password/new(.:format)                   devise/passwords#new
#              edit_user_password GET      /users/password/edit(.:format)                  devise/passwords#edit
#                                 PATCH    /users/password(.:format)                       devise/passwords#update
#                                 PUT      /users/password(.:format)                       devise/passwords#update
#        cancel_user_registration GET      /users/cancel(.:format)                         devise_invitable/registrations#cancel
#               user_registration POST     /users(.:format)                                devise_invitable/registrations#create
#           new_user_registration GET      /users/sign_up(.:format)                        devise_invitable/registrations#new
#          edit_user_registration GET      /users/edit(.:format)                           devise_invitable/registrations#edit
#                                 PATCH    /users(.:format)                                devise_invitable/registrations#update
#                                 PUT      /users(.:format)                                devise_invitable/registrations#update
#                                 DELETE   /users(.:format)                                devise_invitable/registrations#destroy
#          accept_user_invitation GET      /users/invitation/accept(.:format)              devise/invitations#edit
#          remove_user_invitation GET      /users/invitation/remove(.:format)              devise/invitations#destroy
#                 user_invitation POST     /users/invitation(.:format)                     devise/invitations#create
#             new_user_invitation GET      /users/invitation/new(.:format)                 devise/invitations#new
#                                 PATCH    /users/invitation(.:format)                     devise/invitations#update

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <br><br><br>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-default navbar-fixed-top">

<h1 class="logo">

  <a href="#"><img src="<%= asset_path "heart183.png" %>"></a>

</h1>




  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-left">
    <%= render 'layouts/left_navigation_links' %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <%= render 'layouts/right_navigation_links' %>
    </ul>
  </div>
</nav>

 
   
  
    

app/views/layouts/_right_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
<li> <%= link_to "#{current_user.name}", user_path(current_user.id), :class => "sliding-u-l-r" %> </li>
  <li><%= link_to 'LOGOUT', destroy_user_session_path, :method=>'delete', :class => "sliding-u-l-r" %></li>
<% else %>

  <li><%= link_to 'LOGIN', new_user_session_path, :class => "sliding-u-l-r" %></li>
  <li> <%= link_to 'FB LOGIN', user_omniauth_authorize_path(:facebook), :class => "sliding-u-l-r"  %> </li>
<% end %>

<% if user_signed_in? %>
<li><%= link_to 'MAKE RESERVATION', new_user_reservation_path(current_user.id), :class => "sliding-u-l-r" %> </li>

<% else %>
  <li><%= link_to 'SIGN UP', new_user_registration_path, :class => "sliding-u-l-r" %></li>
<% end %>
<% if user_signed_in? %>

  <% if current_user.superadmin? %>

 <li> <%= link_to 'ADMIN DASHBOARD', admin_dashboard_path, :class => "sliding-u-l-r" %> </li>
 <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" sizes="16x16 32x32 48x48 64x64" href="/assets/images/favicon.ico" />
  <link rel="shortcut icon" type="image/x-icon" href="/assets/images/favicon.ico" />
  <link rel="icon" href="/assets/images/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Seat" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Seat" %>">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<!-- Navigation -->
    <div id="headSpace"> </div>
  <header class="container-fluid">
    <%= render 'layouts/navigation' %>
  </header>
<!-- Nav End -->

<!-- Body -->
<div id="main" role="main">
  <div class="col-md-12 text-center">
      <%= render 'layouts/messages' %>
      <%= yield %>       
  </div>
</div>
<!-- Body End -->

<!-- Footer -->
<div id="footer" class="navbar-default">
  <div class="container">
       <p>Your Footer Content Here</p>
  </div>
</div>

<!-- Footer End -->
      
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>

  <script type="text/javascript" src="assets/bootstrap.min.js"></script>
  <script type="text/javascript" src="assets/jquery-1.11.1.min.js"></script>
</html>